trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'Reflyx'
  DOCKERFILE_PATH: 'Dockerfile'
  CONTEXT_PATH: '.'
  TAG: '$(Build.BuildId)'

steps:
- checkout: self
  displayName: 'Checkout code'

- task: AzureCLI@2
  displayName: 'Build, Push, and Deploy'
  inputs:
    azureSubscription: '$(AZURE_SERVICE_CONNECTION)'   # Service connection must exist
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      set -e

      echo "=== Azure Login Complete ==="
      echo "Logging in to ACR..."
      az acr login --name $(ACR_NAME)

      IMAGE_TAG=$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(TAG)
      echo "Building and pushing image: $IMAGE_TAG"
      docker build -f $(DOCKERFILE_PATH) -t $IMAGE_TAG $(CONTEXT_PATH)
      docker push $IMAGE_TAG

      echo "Deploying to Azure Container Apps..."
      # Ensure environment exists
      az containerapp env show \
        --name $(CONTAINERAPPS_ENV) \
        --resource-group $(AZURE_RESOURCE_GROUP) \
        >/dev/null 2>&1 || \
      az containerapp env create \
        --name $(CONTAINERAPPS_ENV) \
        --resource-group $(AZURE_RESOURCE_GROUP) \
        --location $(AZURE_REGION)

      # Create or update Container App
      if az containerapp show --name $(CONTAINERAPPS_NAME) --resource-group $(AZURE_RESOURCE_GROUP) >/dev/null 2>&1; then
        az containerapp update \
          --name $(CONTAINERAPPS_NAME) \
          --resource-group $(AZURE_RESOURCE_GROUP) \
          --image $IMAGE_TAG \
          --ingress external --target-port 8000 \
          --registry-server $(ACR_LOGIN_SERVER) \
          --set-env-vars \
            QDRANT_URL=$(QDRANT_URL) \
            REDIS_URL=$(REDIS_URL) \
            OLLAMA_URL=$(OLLAMA_URL) \
            EMBEDDING_MODEL=$(EMBEDDING_MODEL) \
            CORS_ORIGINS=$(CORS_ORIGINS) \
            LOG_LEVEL=$(LOG_LEVEL) \
            WORKERS=$(WORKERS)
      else
        az containerapp create \
          --name $(CONTAINERAPPS_NAME) \
          --resource-group $(AZURE_RESOURCE_GROUP) \
          --environment $(CONTAINERAPPS_ENV) \
          --image $IMAGE_TAG \
          --ingress external --target-port 8000 \
          --registry-server $(ACR_LOGIN_SERVER) \
          --set-env-vars \
            QDRANT_URL=$(QDRANT_URL) \
            REDIS_URL=$(REDIS_URL) \
            OLLAMA_URL=$(OLLAMA_URL) \
            EMBEDDING_MODEL=$(EMBEDDING_MODEL) \
            CORS_ORIGINS=$(CORS_ORIGINS) \
            LOG_LEVEL=$(LOG_LEVEL) \
            WORKERS=$(WORKERS)
      fi

      FQDN=$(az containerapp show --name $(CONTAINERAPPS_NAME) --resource-group $(AZURE_RESOURCE_GROUP) --query properties.configuration.ingress.fqdn -o tsv)
      echo "=== Backend URL: https://$FQDN ==="
